use datawarehouse1;

-- Retrieve list of unique countries

SELECT DISTINCT Country from gold.dim_customers;

-- Show the first and last order and total duration in months

SELECT 
min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(MONTH,min(order_date),max(order_date)) as datedifferance
FROM gold.fact_sales;

-- Find the youngest and oldest customers based on birthdate

SELECT max(birthdate) as youngest_customer,
datediff(year,max(birthdate),GETDATE()) as youngest_customer_age,
min(birthdate) as oldest_customer,
datediff(year,min(birthdate),GETDATE()) as oldest_customer_age
from gold.dim_customers;



-- Total customers by country!

SELECT 
Country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by count(customer_key) desc;

-- find total customer by gender - ?
SELECT
gender,
Count(customer_key) as total_customers
from gold.dim_customers
group by gender;

-- Find total products by category ?
SELECT 
Category,
Count(product_key) as total_prod_count
from gold.dim_products
group by 
Category

-- What is the avg and total revenue generated by each category

SELECT
p.Category,
avg(p.cost) total_cost_by_cat,
sum(f.sales_amount) total_sales_by_cat
from gold.dim_products p
left join gold.fact_sales f
on p.product_key = f.product_key
group by
p.category
Order by total_sales_by_cat desc;

-- What is the total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
sum(f.sales_amount) as total_sales_by_cust
from gold.dim_customers c
left join gold.fact_sales f
on c.customer_key  = f.customer_key
group by c.customer_key,c.first_name
order by total_sales_by_cust desc;

-- What is the distribution of sold items across countries ?

SELECT
c.Country,
sum(f.quantity)
from gold.dim_customers c
left join gold.fact_sales f
on c.customer_key = f.customer_key
group by c.Country;




-- Which 5 products generate the Highest revenue ?

SELECT top 5 p.product_name,
sum(f.sales_amount) as total_sales_prod
from gold.dim_products p
left join gold.fact_sales f
on p.product_key = f.product_key
group by p.product_name
order by sum(f.sales_amount) desc;

-- Find the top 10 Customers who have generated the highest revenue

-- cust_key, first_name,last_name

SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount)
from gold.dim_customers c
left join gold.fact_sales f
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by sum(f.sales_amount) desc









-- Generat a report that shows all key metrics of the business

SELECT 'Total sales' as measure_name, SUM(sales_amount) as measure_value from gold.fact_sales
union
SELECT 'Average price' as measure_name, avg(price) as measure_value from gold.fact_sales
union
SELECT 'Total Qty' as measure_name,  SUM(quantity) as measure_value from gold.fact_sales
union
SELECT 'Total Orders' as measure_name, count(DISTINCT Order_number) as measure_value from gold.fact_sales
union
SELECT 'Total Products' as measure_name, count(DISTINCT product_name) as measure_value from gold.dim_products
union
SELECT 'Total Customer' as measure_name, count(DISTINCT customer_key) as measure_value from gold.dim_customers
